services:
  ui:
    build:
      context: .
    ports:
      - '4200:4200'
    volumes:
      - .:/barber-shop-ui:delegated
      - /barber-shop-ui/node_modules
    command: ng serve --host 0.0.0.0
    stdin_open: true

